# Generated by Django 4.0.3 on 2022-04-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_rename_announcements_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.TextField(max_length=254),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text_source', models.TextField()),
                ('html_source', tinymce.models.HTMLField()),
                ('send_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
