# Generated by Django 4.0.3 on 2022-04-28 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
