# Generated by Django 4.0.3 on 2022-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.IntegerField(auto_created=0, choices=[(0, 'Idle'), (1, 'Declined'), (2, 'Accepted')], default=0),
        ),
    ]
